noname: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -v -r requirements.txt
  
    - name: Run tests with coverage
      run: pytest --cov=my_package tests/

    - name: Lint with flake8
      run: flake8 my_package tests/
    - name: Type check with mypy
      run: mypy my_package
    - name: Security check with bandit
      run: bandit -r my_package
