name: Python and Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10.1, 3.11]
        node-version: ['20'] # Specify the Node.js version you need, avoiding deprecated ones
        include:
          - python-version: 3.11
            experimental: true

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Node dependencies
      run: |
        npm install

    # Add any steps for building your project here
    # - name: Build project
    #   run: |

    - name: Test with pytest
      run: |
        pytest

    # Include Node.js based tests or build steps if necessary
    # - name: Run Node.js based tests
    #   run: |
    #     npm test

    - name: Experimental Python version warning
      if: matrix.experimental
      run: |
        echo "Tests run on Python ${{ matrix.python-version }} are experimental and might fail due to compatibility issues."
