name: Python CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: |
        pytest ./tests  # Direct pytest to the directory containing your tests, if not in the root directory

    # Optional: Upload coverage report as an artifact (if using pytest-cov)
    - name: Generate coverage report
      run: |
        pytest --cov=./my_package --cov-report=xml  # Replace './my_package' with your package's directory
    - uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
